/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Comprobación de disponibilidad
         * @description Endpoint público: no requiere token.
         */
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usuario autenticado
         * @description Datos y roles del usuario del token. El frontend lo usa para decidir qué mostrar.
         */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar activos
         * @description Paginado, con búsqueda, filtros, orden y sincronización incremental (actualizadoDesde).
         */
        get: operations["ActivosController_findAll"];
        put?: never;
        /** Registrar activo (admin, analista) */
        post: operations["ActivosController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de un activo vigente */
        get: operations["ActivosController_findOne"];
        put?: never;
        post?: never;
        /**
         * Dar de baja un activo (admin)
         * @description Baja lógica: conserva el historial.
         */
        delete: operations["ActivosController_remove"];
        options?: never;
        head?: never;
        /**
         * Modificar activo (admin, analista)
         * @description Solo cambia los campos enviados.
         */
        patch: operations["ActivosController_update"];
        trace?: never;
    };
    "/api/activos/{id}/bitacora": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historial de cambios del activo
         * @description Del más reciente al más antiguo. Disponible también para activos dados de baja.
         */
        get: operations["ActivosController_historial"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categorias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar categorías
         * @description Lista completa, ordenada por nombre (para selectores).
         */
        get: operations["CategoriasController_findAll"];
        put?: never;
        /** Crear categoría (admin) */
        post: operations["CategoriasController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categorias/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Eliminar categoría (admin)
         * @description Solo si ningún activo la usa.
         */
        delete: operations["CategoriasController_remove"];
        options?: never;
        head?: never;
        /** Modificar categoría (admin) */
        patch: operations["CategoriasController_update"];
        trace?: never;
    };
    "/api/criticidades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar niveles de criticidad
         * @description Lista completa (para selectores).
         */
        get: operations["CriticidadesController_findAll"];
        put?: never;
        /** Crear nivel de criticidad (admin) */
        post: operations["CriticidadesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/criticidades/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Eliminar nivel de criticidad (admin)
         * @description Solo si ningún activo lo usa.
         */
        delete: operations["CriticidadesController_remove"];
        options?: never;
        head?: never;
        /** Modificar nivel de criticidad (admin) */
        patch: operations["CriticidadesController_update"];
        trace?: never;
    };
    "/api/respaldos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar respaldos
         * @description Paginado, del más reciente al más antiguo. Filtros por activo, etapa y estados; sincronización incremental con actualizadoDesde.
         */
        get: operations["RespaldosController_findAll"];
        put?: never;
        /**
         * Capa 1 · Definir alcance (admin, analista)
         * @description Crea el respaldo en etapa PENDIENTE_EJECUCION.
         */
        post: operations["RespaldosController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/respaldos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de un respaldo */
        get: operations["RespaldosController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/respaldos/{id}/ejecucion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Capa 2 · Registrar ejecución (admin, analista)
         * @description Solo una vez, mientras la ejecución está PENDIENTE.
         */
        patch: operations["RespaldosController_registrarEjecucion"];
        trace?: never;
    };
    "/api/respaldos/{id}/prueba": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Capa 3 · Registrar restauración/prueba (admin, analista)
         * @description Solo una vez y solo si la ejecución fue EXITOSA.
         */
        patch: operations["RespaldosController_registrarPrueba"];
        trace?: never;
    };
    "/api/mantenimientos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar mantenimientos
         * @description Paginado por fecha programada. Filtros por activo, tipo, fase, estado del equipo, rango de fechas (calendario), vencidos y sincronización incremental.
         */
        get: operations["MantenimientosController_findAll"];
        put?: never;
        /**
         * Programar mantenimiento (admin, analista)
         * @description Crea el mantenimiento en fase PROGRAMADO.
         */
        post: operations["MantenimientosController_programar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mantenimientos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de un mantenimiento */
        get: operations["MantenimientosController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mantenimientos/{id}/iniciar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Iniciar (admin, analista)
         * @description PROGRAMADO → EN_EJECUCION.
         */
        patch: operations["MantenimientosController_iniciar"];
        trace?: never;
    };
    "/api/mantenimientos/{id}/finalizar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Finalizar (admin, analista)
         * @description EN_EJECUCION → FINALIZADO. Registra resultado y estado del equipo.
         */
        patch: operations["MantenimientosController_finalizar"];
        trace?: never;
    };
    "/api/mantenimientos/{id}/cancelar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Cancelar (admin, analista)
         * @description PROGRAMADO o EN_EJECUCION → CANCELADO, con motivo.
         */
        patch: operations["MantenimientosController_cancelar"];
        trace?: never;
    };
    "/api/vulnerabilidades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar vulnerabilidades
         * @description Ordenadas por urgencia: mayor riesgo primero y, dentro del nivel, la más antigua. Filtros por activo, riesgo, estado, CVE, abiertas, vencidas y sincronización incremental.
         */
        get: operations["VulnerabilidadesController_findAll"];
        put?: never;
        /**
         * Registrar vulnerabilidad (admin, analista)
         * @description Crea la vulnerabilidad en estado ABIERTA.
         */
        post: operations["VulnerabilidadesController_registrar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vulnerabilidades/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de una vulnerabilidad */
        get: operations["VulnerabilidadesController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vulnerabilidades/{id}/iniciar-mitigacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Iniciar mitigación (admin, analista)
         * @description ABIERTA → EN_MITIGACION.
         */
        patch: operations["VulnerabilidadesController_iniciarMitigacion"];
        trace?: never;
    };
    "/api/vulnerabilidades/{id}/mitigar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Mitigar (admin, analista)
         * @description EN_MITIGACION → MITIGADA. Registra la acción aplicada y la fecha de cierre.
         */
        patch: operations["VulnerabilidadesController_mitigar"];
        trace?: never;
    };
    "/api/vulnerabilidades/{id}/aceptar-riesgo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Aceptar el riesgo (solo admin)
         * @description ABIERTA o EN_MITIGACION → ACEPTADA. Decisión de gestión: exige justificación.
         */
        patch: operations["VulnerabilidadesController_aceptarRiesgo"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiErrorDto: {
            /** @example 400 */
            statusCode: number;
            /**
             * @description Mensaje o lista de mensajes (p. ej. errores de validación por campo).
             * @example [
             *       "nombre should not be empty"
             *     ]
             */
            message: string | string[];
            /** @example Bad Request */
            error: string;
        };
        AuthUserDto: {
            /**
             * Format: uuid
             * @description ID inmutable del usuario en Keycloak (claim "sub").
             */
            id: string;
            /** @example analista.test */
            username: string;
            /** @example analista.test@gestion-activos.local */
            email?: string;
            /** @example Analista Prueba */
            name?: string;
            /**
             * @example [
             *       "analista"
             *     ]
             */
            roles: ("admin" | "analista" | "auditor")[];
        };
        CategoriaDto: {
            /** @example 1 */
            id: number;
            /** @example Hardware */
            nombre: string;
            /** @example Equipos físicos: servidores, estaciones, periféricos. */
            descripcion: string;
        };
        CriticidadDto: {
            /** @example 3 */
            id: number;
            /** @example Alta */
            nivel: string;
        };
        ActivoDto: {
            /** @example 5 */
            id: number;
            /** @example SRV-001 */
            codigo: string;
            /** @example Servidor de base de datos */
            nombre: string;
            /** @example ERP, Nómina */
            sistemas: string;
            /** @example Área de Infraestructura */
            custodio: string;
            /** @example Centro de datos - Rack 3 */
            ubicacion: string;
            /** @example true */
            cifrado: boolean;
            /** Format: date-time */
            ultimaRevision: string;
            /** @example 1 */
            categoriaId: number;
            /** @example 3 */
            criticidadId: number;
            categoria: components["schemas"]["CategoriaDto"];
            criticidad: components["schemas"]["CriticidadDto"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * Format: date-time
             * @description Fecha de baja; null si el activo está vigente.
             */
            deletedAt: string | null;
        };
        PaginationMetaDto: {
            /** @example 57 */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 20 */
            limit: number;
            /** @example 3 */
            totalPages: number;
        };
        PaginatedActivoDto: {
            data: components["schemas"]["ActivoDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        BitacoraDto: {
            /** @example 12 */
            id: number;
            /** @example 5 */
            activoId: number;
            /**
             * @example ACTUALIZAR
             * @enum {string}
             */
            accion: "CREAR" | "ACTUALIZAR" | "DAR_DE_BAJA";
            /**
             * @description Usuario de Keycloak que hizo el cambio (tomado del token).
             * @example analista.test
             */
            responsable: string;
            /** Format: date-time */
            fecha: string;
            /**
             * @description Campos modificados con su valor anterior y el nuevo.
             * @example {
             *       "ubicacion": {
             *         "antes": "Sala 1",
             *         "despues": "Sala 2"
             *       }
             *     }
             */
            detalle: {
                [key: string]: {
                    antes?: unknown;
                    despues?: unknown;
                };
            };
        };
        PaginatedBitacoraDto: {
            data: components["schemas"]["BitacoraDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        CreateActivoDto: {
            /**
             * @description Código único del activo.
             * @example SRV-001
             */
            codigo: string;
            /** @example Servidor de base de datos */
            nombre: string;
            /**
             * @description Sistemas que soporta o aloja.
             * @example ERP, Nómina
             */
            sistemas: string;
            /**
             * @description Responsable de su custodia.
             * @example Área de Infraestructura
             */
            custodio: string;
            /** @example Centro de datos - Rack 3 */
            ubicacion: string;
            /**
             * @description ¿La información del activo está cifrada?
             * @example true
             */
            cifrado: boolean;
            /**
             * Format: date-time
             * @example 2026-09-15T00:00:00.000Z
             */
            ultimaRevision: string;
            /**
             * @description ID de la categoría (GET /api/categorias).
             * @example 1
             */
            categoriaId: number;
            /**
             * @description ID del nivel de criticidad (GET /api/criticidades).
             * @example 3
             */
            criticidadId: number;
        };
        UpdateActivoDto: {
            /**
             * @description Código único del activo.
             * @example SRV-001
             */
            codigo?: string;
            /** @example Servidor de base de datos */
            nombre?: string;
            /**
             * @description Sistemas que soporta o aloja.
             * @example ERP, Nómina
             */
            sistemas?: string;
            /**
             * @description Responsable de su custodia.
             * @example Área de Infraestructura
             */
            custodio?: string;
            /** @example Centro de datos - Rack 3 */
            ubicacion?: string;
            /**
             * @description ¿La información del activo está cifrada?
             * @example true
             */
            cifrado?: boolean;
            /**
             * Format: date-time
             * @example 2026-09-15T00:00:00.000Z
             */
            ultimaRevision?: string;
            /**
             * @description ID de la categoría (GET /api/categorias).
             * @example 1
             */
            categoriaId?: number;
            /**
             * @description ID del nivel de criticidad (GET /api/criticidades).
             * @example 3
             */
            criticidadId?: number;
        };
        CreateCategoriaDto: {
            /** @example Hardware */
            nombre: string;
            /** @example Equipos físicos: servidores, estaciones, periféricos. */
            descripcion: string;
        };
        UpdateCategoriaDto: {
            /** @example Hardware */
            nombre?: string;
            /** @example Equipos físicos: servidores, estaciones, periféricos. */
            descripcion?: string;
        };
        CreateCriticidadDto: {
            /** @example Alta */
            nivel: string;
        };
        UpdateCriticidadDto: {
            /** @example Alta */
            nivel?: string;
        };
        ActivoResumenDto: {
            /** @example 5 */
            id: number;
            /** @example SRV-001 */
            codigo: string;
            /** @example Servidor de base de datos */
            nombre: string;
        };
        RespaldoDto: {
            /** @example 1 */
            id: number;
            /** @example 5 */
            activoId: number;
            activo: components["schemas"]["ActivoResumenDto"];
            /**
             * @description Etapa del ciclo de vida, derivada de los dos estados.
             * @enum {string}
             */
            etapa: "PENDIENTE_EJECUCION" | "EJECUCION_FALLIDA" | "PENDIENTE_PRUEBA" | "PRUEBA_FALLIDA" | "COMPLETADO";
            /** @example Base de datos ERP completa */
            alcanceDetalle: string;
            /** @enum {string} */
            estadoEjecucion: "PENDIENTE" | "EXITOSA" | "FALLIDA";
            /** Format: date-time */
            fechaEjecucion: string | null;
            rutaEvidencia: string | null;
            /** @enum {string} */
            estadoPrueba: "PENDIENTE" | "APROBADA" | "FALLIDA";
            resultadoPrueba: string | null;
            /** Format: date-time */
            fechaPrueba: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PaginatedRespaldoDto: {
            data: components["schemas"]["RespaldoDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        CreateRespaldoDto: {
            /**
             * @description ID de un activo vigente.
             * @example 5
             */
            activoId: number;
            /** @example Base de datos ERP completa + archivos de configuración */
            alcanceDetalle: string;
        };
        RegistrarEjecucionDto: {
            /** @enum {string} */
            estadoEjecucion: "EXITOSA" | "FALLIDA";
            /**
             * Format: date-time
             * @example 2026-09-30T02:00:00.000Z
             */
            fechaEjecucion: string;
            /**
             * @description URL o ruta de red donde está la evidencia (log, captura...).
             * @example \\nas01\respaldos\erp\2026-09-30.log
             */
            rutaEvidencia: string;
        };
        RegistrarPruebaDto: {
            /** @enum {string} */
            estadoPrueba: "APROBADA" | "FALLIDA";
            /** @example Restauración completa en entorno de pruebas en 42 min; datos íntegros. */
            resultadoPrueba: string;
            /**
             * Format: date-time
             * @example 2026-09-30T10:00:00.000Z
             */
            fechaPrueba: string;
        };
        ActivoMantenidoDto: {
            /** @example 5 */
            id: number;
            /** @example SRV-001 */
            codigo: string;
            /** @example Servidor de base de datos */
            nombre: string;
        };
        MantenimientoDto: {
            /** @example 1 */
            id: number;
            /** @example 5 */
            activoId: number;
            activo: components["schemas"]["ActivoMantenidoDto"];
            /** @enum {string} */
            tipo: "PREVENTIVO" | "CORRECTIVO";
            /** @enum {string} */
            fase: "PROGRAMADO" | "EN_EJECUCION" | "FINALIZADO" | "CANCELADO";
            /**
             * @description PROGRAMADO con fecha ya pasada (calculado).
             * @example false
             */
            vencido: boolean;
            /** @example Limpieza interna y actualización de firmware */
            actividad: string;
            /**
             * Format: date-time
             * @description Fecha programada.
             */
            fecha: string;
            /** Format: date-time */
            fechaInicio: string | null;
            /** Format: date-time */
            fechaFin: string | null;
            /**
             * @description Se registra al finalizar.
             * @enum {string|null}
             */
            estadoEquipo: "OPERATIVO" | "DEGRADADO" | "FUERA_DE_SERVICIO" | null;
            /** @description Resultado al finalizar o motivo al cancelar. */
            resultado: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PaginatedMantenimientoDto: {
            data: components["schemas"]["MantenimientoDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        ProgramarMantenimientoDto: {
            /**
             * @description ID de un activo vigente.
             * @example 5
             */
            activoId: number;
            /**
             * @example PREVENTIVO
             * @enum {string}
             */
            tipo: "PREVENTIVO" | "CORRECTIVO";
            /** @example Limpieza interna y actualización de firmware */
            actividad: string;
            /**
             * Format: date-time
             * @description Fecha programada (puede ser futura).
             * @example 2026-10-15T08:00:00.000Z
             */
            fecha: string;
        };
        IniciarMantenimientoDto: {
            /**
             * Format: date-time
             * @description Si no se envía, se usa la hora actual del servidor.
             */
            fechaInicio?: string;
        };
        FinalizarMantenimientoDto: {
            /** @example Firmware actualizado a v2.4; sin incidencias. */
            resultado: string;
            /**
             * @description Cómo quedó el equipo tras el mantenimiento.
             * @example OPERATIVO
             * @enum {string}
             */
            estadoEquipo: "OPERATIVO" | "DEGRADADO" | "FUERA_DE_SERVICIO";
            /**
             * Format: date-time
             * @description Si no se envía, se usa la hora actual del servidor.
             */
            fechaFin?: string;
        };
        CancelarMantenimientoDto: {
            /**
             * @description Motivo de la cancelación (se guarda como resultado).
             * @example El proveedor reprogramó la visita.
             */
            motivo: string;
        };
        ActivoAfectadoDto: {
            /** @example 5 */
            id: number;
            /** @example SRV-001 */
            codigo: string;
            /** @example Servidor de base de datos */
            nombre: string;
        };
        VulnerabilidadDto: {
            /** @example 1 */
            id: number;
            /** @example 5 */
            activoId: number;
            activo: components["schemas"]["ActivoAfectadoDto"];
            /** @example CVE-2026-12345 */
            cve: string | null;
            descripcion: string;
            /** @enum {string} */
            nivelRiesgo: "BAJO" | "MEDIO" | "ALTO" | "CRITICO";
            /** @enum {string} */
            estado: "ABIERTA" | "EN_MITIGACION" | "MITIGADA" | "ACEPTADA";
            /**
             * @description Pendiente y con la fecha límite ya pasada (calculado).
             * @example false
             */
            vencida: boolean;
            /** @description Acción aplicada al mitigar, o justificación al aceptar el riesgo. */
            mitigacion: string | null;
            /**
             * Format: date-time
             * @description Fecha de detección.
             */
            fecha: string;
            /** Format: date-time */
            fechaLimite: string | null;
            /**
             * Format: date-time
             * @description Se registra automáticamente al mitigar o aceptar el riesgo.
             */
            fechaCierre: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PaginatedVulnerabilidadDto: {
            data: components["schemas"]["VulnerabilidadDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        RegistrarVulnerabilidadDto: {
            /**
             * @description ID de un activo vigente.
             * @example 5
             */
            activoId: number;
            /**
             * @description Identificador público (se normaliza a mayúsculas).
             * @example CVE-2026-12345
             */
            cve?: string;
            /** @example OpenSSL 3.0.x vulnerable a desbordamiento de búfer en la verificación de certificados X.509. */
            descripcion: string;
            /**
             * @example ALTO
             * @enum {string}
             */
            nivelRiesgo: "BAJO" | "MEDIO" | "ALTO" | "CRITICO";
            /**
             * Format: date-time
             * @description Fecha de detección (no puede ser futura).
             * @example 2026-09-30T09:00:00.000Z
             */
            fecha: string;
            /**
             * Format: date-time
             * @description Plazo para remediarla (SLA). No puede ser anterior a la detección.
             * @example 2026-10-15T23:59:59.000Z
             */
            fechaLimite?: string;
        };
        MitigarVulnerabilidadDto: {
            /** @example Actualizado OpenSSL a 3.0.15 y reiniciado el servicio; verificado con escaneo. */
            mitigacion: string;
        };
        AceptarRiesgoDto: {
            /**
             * @description Justificación formal (se guarda en "mitigacion").
             * @example Sistema heredado sin parche del fabricante; aislado en VLAN sin acceso a Internet. Se reevalúa en 6 meses.
             */
            justificacion: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserDto"];
                };
            };
            /** @description Token ausente, inválido o expirado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    ActivosController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Busca en código, nombre, custodio y ubicación. */
                q?: string;
                categoriaId?: number;
                criticidadId?: number;
                /** @description Filtra por activos cifrados (true) o sin cifrar (false). */
                cifrado?: boolean;
                sort?: "codigo" | "nombre" | "custodio" | "ubicacion" | "ultimaRevision" | "createdAt" | "updatedAt";
                order?: "asc" | "desc";
                /** @description Sincronización incremental: solo activos modificados DESPUÉS de esta fecha. Incluye los dados de baja (deletedAt ≠ null) para que el frontend los retire. */
                actualizadoDesde?: string;
                /** @description Incluir activos dados de baja. */
                incluirBajas?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedActivoDto"];
                };
            };
            /** @description Parámetros de consulta inválidos. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    ActivosController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateActivoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivoDto"];
                };
            };
            /** @description Datos inválidos o categoría/criticidad inexistente. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description El código ya existe. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    ActivosController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivoDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    ActivosController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    ActivosController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateActivoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivoDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description El código ya existe. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    ActivosController_historial: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBitacoraDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    CategoriasController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaDto"][];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    CategoriasController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoriaDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description El nombre ya existe. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    CategoriasController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Hay activos con esta categoría. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    CategoriasController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoriaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description El nombre ya existe. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    CriticidadesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriticidadDto"][];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    CriticidadesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCriticidadDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriticidadDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description El nivel ya existe. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    CriticidadesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Hay activos con este nivel. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    CriticidadesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCriticidadDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriticidadDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description El nivel ya existe. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    RespaldosController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Respaldos de un activo. */
                activoId?: number;
                /** @description P. ej. PENDIENTE_PRUEBA = ejecutados con éxito que falta probar. */
                etapa?: "PENDIENTE_EJECUCION" | "EJECUCION_FALLIDA" | "PENDIENTE_PRUEBA" | "PRUEBA_FALLIDA" | "COMPLETADO";
                estadoEjecucion?: "PENDIENTE" | "EXITOSA" | "FALLIDA";
                estadoPrueba?: "PENDIENTE" | "APROBADA" | "FALLIDA";
                /** @description Sincronización incremental: solo respaldos modificados después de esta fecha. */
                actualizadoDesde?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRespaldoDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    RespaldosController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRespaldoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespaldoDto"];
                };
            };
            /** @description Datos inválidos o activo inexistente/dado de baja. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    RespaldosController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespaldoDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    RespaldosController_registrarEjecucion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarEjecucionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespaldoDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description La ejecución ya fue registrada. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    RespaldosController_registrarPrueba: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarPruebaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespaldoDto"];
                };
            };
            /** @description Datos inválidos o fecha anterior a la ejecución. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Ejecución no exitosa o prueba ya registrada. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    MantenimientosController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                activoId?: number;
                tipo?: "PREVENTIVO" | "CORRECTIVO";
                fase?: "PROGRAMADO" | "EN_EJECUCION" | "FINALIZADO" | "CANCELADO";
                estadoEquipo?: "OPERATIVO" | "DEGRADADO" | "FUERA_DE_SERVICIO";
                /** @description Fecha programada desde (incluida). Útil para calendarios. */
                desde?: string;
                /** @description Fecha programada hasta (incluida). */
                hasta?: string;
                /** @description true = solo PROGRAMADOS con fecha pasada; false = excluirlos. */
                vencidos?: boolean;
                /** @description Orden por fecha programada. */
                order?: "asc" | "desc";
                /** @description Sincronización incremental: solo mantenimientos modificados después de esta fecha. */
                actualizadoDesde?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMantenimientoDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    MantenimientosController_programar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgramarMantenimientoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MantenimientoDto"];
                };
            };
            /** @description Datos inválidos o activo inexistente/dado de baja. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    MantenimientosController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MantenimientoDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    MantenimientosController_iniciar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IniciarMantenimientoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MantenimientoDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Fase no permitida. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    MantenimientosController_finalizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinalizarMantenimientoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MantenimientoDto"];
                };
            };
            /** @description Datos inválidos o fecha de fin anterior al inicio. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Fase no permitida. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    MantenimientosController_cancelar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelarMantenimientoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MantenimientoDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Fase no permitida. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    VulnerabilidadesController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                activoId?: number;
                nivelRiesgo?: "BAJO" | "MEDIO" | "ALTO" | "CRITICO";
                estado?: "ABIERTA" | "EN_MITIGACION" | "MITIGADA" | "ACEPTADA";
                /** @description Busca por CVE (coincidencia parcial). */
                cve?: string;
                /** @description true = solo pendientes (ABIERTA o EN_MITIGACION); false = solo cerradas. */
                abiertas?: boolean;
                /** @description true = solo pendientes con fecha límite ya pasada (SLA incumplido); false = excluirlas. */
                vencidas?: boolean;
                /** @description Sincronización incremental: solo vulnerabilidades modificadas después de esta fecha. */
                actualizadoDesde?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedVulnerabilidadDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    VulnerabilidadesController_registrar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarVulnerabilidadDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VulnerabilidadDto"];
                };
            };
            /** @description Datos inválidos, CVE mal formado, fecha límite anterior a la detección o activo inexistente/dado de baja. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description El activo ya tiene ese CVE pendiente. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    VulnerabilidadesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VulnerabilidadDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    VulnerabilidadesController_iniciarMitigacion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VulnerabilidadDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Estado no permitido. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    VulnerabilidadesController_mitigar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MitigarVulnerabilidadDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VulnerabilidadDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Estado no permitido. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    VulnerabilidadesController_aceptarRiesgo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AceptarRiesgoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VulnerabilidadDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Token ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Rol insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
            /** @description Estado no permitido. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
}
